In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv("data.csv", parse_dates=['Date'],
                 encoding="ISO-8859-1",
                 dtype={"RegionName": str,
                        "RegionCode": str},
                 error_bad_lines=False)
pred = pd.read_csv("predictions.csv", 
                   parse_dates=['Date'],
                   encoding="ISO-8859-1",
                   dtype={"RegionName": str,
                          "RegionCode": str},
                   error_bad_lines=False)

In [9]:
df

,CountryName,RegionName,Date,PredictedDailyNewCases,Unnamed: 0,CountryCode,RegionCode,C1_School closing,C1_Flag,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,NaN,2020-01-01,59.435110,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aruba,NaN,2020-01-02,76.294088,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aruba,NaN,2020-01-03,82.705463,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aruba,NaN,2020-01-04,87.574387,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aruba,NaN,2020-01-05,87.930059,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79375,Zimbabwe,NaN,2020-11-15,NaN,79375.0,ZWE,NaN,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79376,Zimbabwe,NaN,2020-11-16,NaN,79376.0,ZWE,NaN,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79377,Zimbabwe,NaN,2020-11-17,NaN,79377.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79378,Zimbabwe,NaN,2020-11-18,NaN,79378.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79379,Zimbabwe,NaN,2020-11-19,NaN,79379.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0

In [7]:
df

,CountryName,RegionName,Date,PredictedDailyNewCases,Unnamed: 0,CountryCode,RegionCode,C1_School closing,C1_Flag,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,NaN,2020-01-01,59.435110,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aruba,NaN,2020-01-02,76.294088,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aruba,NaN,2020-01-03,82.705463,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aruba,NaN,2020-01-04,87.574387,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aruba,NaN,2020-01-05,87.930059,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79375,Zimbabwe,NaN,2020-11-15,NaN,79375.0,ZWE,NaN,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79376,Zimbabwe,NaN,2020-11-16,NaN,79376.0,ZWE,NaN,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79377,Zimbabwe,NaN,2020-11-17,NaN,79377.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79378,Zimbabwe,NaN,2020-11-18,NaN,79378.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79379,Zimbabwe,NaN,2020-11-19,NaN,79379.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0