In [1]:
import pandas as pd
import numpy as np
import pylab as plt

In [12]:
df = pd.read_csv("data.csv", parse_dates=['Date'],
			 encoding="ISO-8859-1",
			 dtype={"RegionName": str,
			        "RegionCode": str},
			 error_bad_lines=False)
pred = pd.read_csv("predictions.csv", parse_dates=['Date'],
			 encoding="ISO-8859-1",
			 dtype={"RegionName": str,
			        "RegionCode": str},
			 error_bad_lines=False))

In [13]:
df

,Unnamed: 0,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,0,Aruba,ABW,NaN,NaN,2020-01-01,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,1,Aruba,ABW,NaN,NaN,2020-01-02,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2,2,Aruba,ABW,NaN,NaN,2020-01-03,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
3,3,Aruba,ABW,NaN,NaN,2020-01-04,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
4,4,Aruba,ABW,NaN,NaN,2020-01-05,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79375,79375,Zimbabwe,ZWE,NaN,NaN,2020-11-15,1.0,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79376,79376,Zimbabwe,ZWE,NaN,NaN,2020-11-16,1.0,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79377,79377,Zimbabwe,ZWE,NaN,NaN,2020-11-17,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79378,79378,Zimbabwe,ZWE,NaN,NaN,2020-11-18,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79379,79379,Zimbabwe,ZWE,NaN,NaN,2020-11-19,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0

In [14]:
pred

   CountryName  RegionName        Date  PredictedDailyNewCases
0        India         NaN  2021-01-01            39206.726721
1        India         NaN  2021-01-02            40074.392801
2        India         NaN  2021-01-03            37283.227754
3        India         NaN  2021-01-04            27286.932844
4        India         NaN  2021-01-05            26307.500986
..         ...         ...         ...                     ...
57      Mexico         NaN  2021-01-27              665.456354
58      Mexico         NaN  2021-01-28             5861.357197
59      Mexico         NaN  2021-01-29             3987.442635
60      Mexico         NaN  2021-01-30             4061.119631
61      Mexico         NaN  2021-01-31             4491.328723

[62 rows x 4 columns]

In [15]:
df.join(pred, on="Date")

ValueError: You are trying to merge on datetime64[ns] and int64 columns. If you wish to proceed you should use pd.concat