In [25]:
import pandas as pd
import numpy as np
import pylab as plt

In [26]:
df = pd.read_csv("data.csv", parse_dates=['Date'],
              encoding="ISO-8859-1",
              dtype={"RegionName": str,
                     "RegionCode": str},
              error_bad_lines=False)
pred = pd.read_csv("predictions.csv", 
                   parse_dates=['Date'],
                   encoding="ISO-8859-1",
                   dtype={"RegionName": str,
                          "RegionCode": str},
                   error_bad_lines=False)

In [28]:
df = pd.concat([pred, df])

In [29]:
df

,CountryName,RegionName,Date,PredictedDailyNewCases,Unnamed: 0,CountryCode,RegionCode,C1_School closing,C1_Flag,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,NaN,2020-08-01,6.996833,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aruba,NaN,2020-08-02,6.293248,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aruba,NaN,2020-08-03,9.389845,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aruba,NaN,2020-08-04,6.418767,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,NaN,2020-08-01,158.260836,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79375,Zimbabwe,NaN,2020-11-15,NaN,79375.0,ZWE,NaN,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79376,Zimbabwe,NaN,2020-11-16,NaN,79376.0,ZWE,NaN,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79377,Zimbabwe,NaN,2020-11-17,NaN,79377.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79378,Zimbabwe,NaN,2020-11-18,NaN,79378.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79379,Zimbabwe,NaN,2020-11-19,NaN,79379.0,ZWE,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0

In [14]:
df

,Unnamed: 0,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,0,Aruba,ABW,NaN,NaN,2020-01-01,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,1,Aruba,ABW,NaN,NaN,2020-01-02,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2,2,Aruba,ABW,NaN,NaN,2020-01-03,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
3,3,Aruba,ABW,NaN,NaN,2020-01-04,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
4,4,Aruba,ABW,NaN,NaN,2020-01-05,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79375,79375,Zimbabwe,ZWE,NaN,NaN,2020-11-15,1.0,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79376,79376,Zimbabwe,ZWE,NaN,NaN,2020-11-16,1.0,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79377,79377,Zimbabwe,ZWE,NaN,NaN,2020-11-17,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79378,79378,Zimbabwe,ZWE,NaN,NaN,2020-11-18,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79379,79379,Zimbabwe,ZWE,NaN,NaN,2020-11-19,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0