In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
data = pd.read_csv("data.csv", parse_dates=['Date'],
                 encoding="ISO-8859-1",
                 dtype={"RegionName": str,
                        "RegionCode": str},
                 error_bad_lines=False)
pred = pd.read_csv("predictions.csv", 
                   parse_dates=['Date'],
                   encoding="ISO-8859-1",
                   dtype={"RegionName": str,
                          "RegionCode": str},
                   error_bad_lines=False)

In [11]:
df = pd.concat([data, pred])

In [16]:
data

,Unnamed: 0,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,0,Aruba,ABW,NaN,NaN,2020-01-01,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,1,Aruba,ABW,NaN,NaN,2020-01-02,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2,2,Aruba,ABW,NaN,NaN,2020-01-03,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
3,3,Aruba,ABW,NaN,NaN,2020-01-04,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
4,4,Aruba,ABW,NaN,NaN,2020-01-05,0.0,NaN,0.0,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79375,79375,Zimbabwe,ZWE,NaN,NaN,2020-11-15,1.0,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79376,79376,Zimbabwe,ZWE,NaN,NaN,2020-11-16,1.0,1.0,1.0,1.0,...,67.59,67.59,73.81,73.81,58.33,58.33,63.89,63.89,25.0,25.0
79377,79377,Zimbabwe,ZWE,NaN,NaN,2020-11-17,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79378,79378,Zimbabwe,ZWE,NaN,NaN,2020-11-18,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0
79379,79379,Zimbabwe,ZWE,NaN,NaN,2020-11-19,NaN,NaN,NaN,NaN,...,NaN,67.59,NaN,73.81,NaN,58.33,NaN,63.89,NaN,25.0

In [14]:
pred

      CountryName RegionName       Date  PredictedDailyNewCases
0           Aruba        NaN 2020-01-01               59.435110
1           Aruba        NaN 2020-01-02               76.294088
2           Aruba        NaN 2020-01-03               82.705463
3           Aruba        NaN 2020-01-04               87.574387
4           Aruba        NaN 2020-01-05               87.930059
...           ...        ...        ...                     ...
66577    Zimbabwe        NaN 2020-09-26            85773.588113
66578    Zimbabwe        NaN 2020-09-27            87378.851981
66579    Zimbabwe        NaN 2020-09-28            89014.062592
66580    Zimbabwe        NaN 2020-09-29            90679.707948
66581    Zimbabwe        NaN 2020-09-30            92376.229481

[66582 rows x 4 columns]

In [15]:
df

,Unnamed: 0,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay,PredictedDailyNewCases
0,0.0,Aruba,ABW,NaN,NaN,2020-01-01,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,1.0,Aruba,ABW,NaN,NaN,2020-01-02,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,2.0,Aruba,ABW,NaN,NaN,2020-01-03,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,3.0,Aruba,ABW,NaN,NaN,2020-01-04,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,4.0,Aruba,ABW,NaN,NaN,2020-01-05,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66577,NaN,Zimbabwe,NaN,NaN,NaN,2020-09-26,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85773.588113
66578,NaN,Zimbabwe,NaN,NaN,NaN,2020-09-27,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87378.851981
66579,NaN,Zimbabwe,NaN,NaN,NaN,2020-09-28,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89014.062592
66580,NaN,Zimbabwe,NaN,NaN,NaN,2020-09-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90679.707948
66581,NaN,Zimbabwe,NaN,NaN,NaN,2020-09-30,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92376.229481